[package]
name = "earcut"
version = "1.0.0"
authors = ["John Firebaugh <john@mapbox.com>"]

[lib]
crate-type = ["cdylib"]

[dependencies]
typed-arena = "1.3.0"
itertools = "0.7.6"
wasm-bindgen = "0.2"

[dev-dependencies]
serde = "1.0.66"
serde_json = "1.0.20"

[profile.release]
debug = true
